# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Rattan vNIC Kernel Module Development VM (libvirt)
#
# Prerequisites:
#   sudo apt install vagrant libvirt-daemon-system vagrant-libvirt
#   sudo usermod -aG libvirt $USER
#   newgrp libvirt  # or logout/login
#
# Usage:
#   cd rvnic/kernel/
#   vagrant up              - Create and provision the VM (default: debian13)
#   vagrant ssh             - SSH into the VM
#   vagrant halt            - Stop the VM
#   vagrant destroy         - Remove the VM
#   vagrant rsync-auto      - Auto-sync on file changes (if using rsync)
#
# Inside VM:
#   cd /rattan              - Access the full rattan project
#   cd /rattan/rvnic/kernel - Kernel module directory
#   make                    - Build the kernel module
#   sudo insmod rattan_vnic.ko  - Load the module
#   sudo rmmod rattan_vnic      - Unload the module
#   dmesg | tail            - Check kernel messages
#


Vagrant.configure("2") do |config|
  # Base box
  config.vm.box = "behemoth/debian13"
  
  config.vm.hostname = "rattan-dev"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.synced_folder ".", "/home/vagrant/rvnic",
    type: "rsync",
    rsync__auto: true,  
    rsync__include: ["rattan_vnic.ko"]
    
  config.vm.synced_folder "../librvnic/target/release/examples", "/home/vagrant/examples",
    type: "rsync",
    rsync__auto: true,  
    rsync__include: ["test_forward", "test_forward_drop", "test_forward_multiqueue", "test_umem"]

  # Libvirt provider configuration
  config.vm.provider "libvirt" do |lv|

    lv.memory = 4096
    lv.cpus = 16

    lv.driver = "kvm"
    lv.nested = true

    lv.cpu_mode = "host-passthrough"
    # lv.machine_virtual_size = 128 # 128GB 

  end
  
  # Provisioning script
  config.vm.provision "shell", inline: <<-SHELL
    # Update package lists
    apt-get update

    # 1. System Essentials (Keep for stability)
    apt-get install -y libpam-systemd libnss-systemd systemd-timesyncd
    
    # 2. Network Experiment Tools

    apt-get install -y \
      bash-completion \
      bridge-utils \
      bzip2 \
      bpftrace \
      ca-certificates \
      dbus \
      ethtool \
      file \
      gettext-base \
      gnupg \
      htop \
      iproute2 \
      iputils-ping \
      liblockfile-bin \
      lsof \
      ltrace \
      lvm2 \
      media-types \
      ncurses-term \
      netcat-traditional \
      openssh-client \
      perl \
      psmisc \
      rsync \
      socat \
      ssl-cert \
      strace \
      tcpdump \
      traceroute \
      util-linux-extra \
      xz-utils
      
    DEBIAN_FRONTEND=noninteractive apt-get install -y iperf3
    
    # 3. Update to the newest kernel
    apt-get install linux-image-amd64 linux-headers-amd64
    
  SHELL
  
end
