[profile.ci]
retries = { backoff = "fixed", count = 2, delay = "1s" }
fail-fast = false
failure-output = "immediate-final"
leak-timeout = "1s"
slow-timeout = { period = "60s", terminate-after = 2, grace-period = "30s" }
