name: Build

on:
  push:
    paths-ignore:
      - 'documents/**'
      - '.github/**'
      - 'assets/**'
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: cargo build with all features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt update && sudo apt install ethtool iputils-ping iperf iperf3 pkg-config m4 clang llvm libelf-dev libpcap-dev gcc-multilib -y
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --workspace --all-features
      - run: cargo build --workspace --all-features

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: sudo apt update && sudo apt install ethtool iputils-ping iperf iperf3 pkg-config m4 clang llvm libelf-dev libpcap-dev gcc-multilib -y
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --workspace --all-features --tests -- -Dwarnings
      # - uses: giraffate/clippy-action@v1
      #   with:
      #     reporter: 'github-pr-review'
      #     clippy_flags: --workspace --all-features --tests

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  audit:
    name: Run cargo audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rust-lang/audit@v1
